---
apiVersion: v1
kind: Namespace
metadata:
  name: 10sr-playground
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-nodeport
  namespace: 10sr-playground
spec:
  type: NodePort
  selector:
    app: webtools
  ports:
    - protocol: TCP
      port: 7700
      nodePort: 30077
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: 10sr-playground
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-deployment
  namespace: 10sr-playground
  labels:
    app: webtools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webtools
  template:
    metadata:
      labels:
        app: webtools
    spec:
      containers:
        - name: webtools
          image: quay.io/10sr/webtools:v0.0.8
          ports:
            - containerPort: 7700
          env:
            - name: WEBTOOLS_SETTINGS_TOML
              value: ./settings_insecure.toml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: 10sr-playground
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
