# Namespaces

---
apiVersion: v1
kind: Namespace
metadata:
  name: kexample
---
apiVersion: v1
kind: Namespace
metadata:
  name: exposed
---
apiVersion: v1
kind: Namespace
metadata:
  name: internal


# PersistentVolumes

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv01
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: slow
  nfs:
    path: /var/lib/data/nfs/kubernetes/pv01
    # TODO: Parameterize
    server: 160.16.142.176
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv02
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: slow
  nfs:
    path: /var/lib/data/nfs/kubernetes/pv02
    # TODO: Parameterize
    server: 160.16.142.176
