---
apiVersion: v1
kind: Namespace
metadata:
  name: 10sr-playground
  

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: 10sr-playground
spec:
  type: NodePort
  selector:
    app: nginx
  ports:    - protocol: TCP
      port: 80
      nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: helloapp-nodeport
  namespace: 10sr-playground
spec:
  type: NodePort
  selector:
    app: helloapp
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: 10sr-playground
data:
  nginx_index_html: |
    nginx of k8s
    10sr-playground
  nginx_cmd_sh: |
    #!/bin/sh
    set -eux
    cp -pf /configmap_volume/nginx_index_html /usr/share/nginx/html/index.html
    echo `hostname` >>/usr/share/nginx/html/index.html
    exec nginx -g "daemon off;"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: 10sr-playground
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          args: [ "sh", "/configmap_volume/nginx_cmd_sh" ]
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - name: nginx-configmap-volume
              mountPath: /configmap_volume
      volumes:
        - name: nginx-configmap-volume
          configMap:
            name: nginx-configmap
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
  namespace: 10sr-playground
  labels:
    app: helloapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
        - name: helloapp
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
