---
- name: Add alias for root
  lineinfile:
    dest: /etc/aliases
    regexp: "^root"
    line: "root: {{ postfix_root_alias }},root"
  become: yes
  register: _postfix_aliases

- name: Update aliases.db
  command: newaliases
  become: yes
  when: _postfix_aliases is changed
