---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml
# bases:
#   - base

namespace: exposed
commonLabels:
  kustomize: prom
namePrefix: prom-

configMapGenerator:
  - name: files-configmap
    files:
      - files/alertmanager.yml.envsubst
      - files/nginx.conf
      - files/ngins_cmd.sh
      - files/prometheus.yml.envsubst
      - files/rules.yml
      - files/up.sh

vars:
  - name: PROM_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: prom-service
    fieldref:
      fieldpath: metadata.name
