---
# Disable for now. 10sr.mdyns.jp is directed to ec2 instance.
# - template:
#     src: regtomydns.sh.j2
#     mode: 0755
#     dest: /etc/cron.daily/regtomydns
#   when: secret.ddns_mydns_password != ""
#   become: yes

# - name: Check if regtomydns works
#   command: /etc/cron.daily/regtomydns
#   when: secret.ddns_mydns_password != ""
#   changed_when: False


- template:
    src: _update_f5_si.sh.j2
    dest: /usr/local/bin/_update_f5_si.sh
  become: yes

- cron:
    name: Update f5.si DDNS entry
    hour: 5
    minute: 50
    job: sh /usr/local/bin/_update_f5_si.sh
    user: root
  become: yes
