---
- name: Put cloudera repo file
  template:
    src: cloudera-manager.repo.j2
    dest: /etc/yum.repos.d/cloudera-manager.repo
  become: yes

- name: Install oracle jdk
  yum:
    name: oracle-j2sdk1.7
    update_cache: yes
  become: yes

- name: Install mysql-connector for /usr/share/cmf/schema/scm_prepare_database.sh
  yum:
    name: mysql-connector-java
    update_cache: yes
  become: yes

- name: Install pstree, required for cloudera-scm-server start
  yum:
    name: psmisc
    update_cache: yes
  become: yes

- name: Install cloudera manager packages
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - cloudera-manager-server
    - cloudera-manager-daemons
  become: yes

#   # https://www.cloudera.com/documentation/enterprise/5-10-x/topics/cm_ig_installing_configuring_dbs.html#concept_i2r_m3m_hn
# - name: Put db.properties
#   template:
#     src: db.properties.j2
#     dest: /etc/cloudera-scm-server/db.properties
#   become: yes
