---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml
# bases:
#   - base

namespace: exposed
commonLabels:
  kustomize: webtools
namePrefix: webtools-

configMapGenerator:
  - name: configmap-from-file-content
    files:
      - files/nginx_cmd.sh
      - files/nginx_index.html
