---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 30009

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /export
            - --address
            - 0.0.0.0:9000
          ports:
            - containerPort: 9000
              hostPort: 9000
          env:
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-from-file
                  key: minio_secret_key
            - name: MINIO_ACCESS_KEY
              value: 17C2C6DB
          volumeMounts:
            - name: export-hostpath
              mountPath: /export
            - name: config-hostpath
              mountPath: /root/.minio
      volumes:
        - name: export-hostpath
          hostPath:
            path: /var/lib/data/kubernetes-hostpath/exposed.webtools/minio/export
            type: Directory
        - name: config-hostpath
          hostPath:
            path: /var/lib/data/kubernetes-hostpath/exposed.webtools/minio/config
            type: Directory
