---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - port: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /export
          volumeMounts:
            - name: export-hostpath
              mountPath: /export
            - name: config-hostpath
              mountPath: /root/.minio
      volumes:
        - name: export-hostpath
          hostPath:
            path: /var/lib/data/kubernetes-hostpath/exposed.webtools/minio/export
            type: Directory
        - name: config-hostpath
          hostPath:
            path: /var/lib/data/kubernetes-hostpath/exposed.webtools/minio/config
            type: Directory
