---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    service: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  selector:
    service: minio
  ports:
    - port: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - name: redis
          image: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    service: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      service: minio
  template:
    metadata:
      labels:
        service: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /export
          volumeMounts:
            - name: export-hostpath
              mountPath: /export
      volumes:
        - name: export-hostpath
          hostPath:
            path: /var/lib/data/kubernetes-hostpath/exposed.webtools/minio/export
            type: Directory
