---
- name: Base Configurations
  hosts: default
  vars:
    _internal_network:
      conn_name: eth1
      ifname: eth1
      gw4: 172.16.100.1
      subnetmask_prefix: 24
    _internal_hosts:
      # Keys should be ansible target hosts (inventory_hostname)
      fugen01:
        name: fugen01.3ends.info
        ipv4: 172.16.100.100

  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

    - name: Set ansible_become_pass
      set_fact:
        ansible_become_pass: "{{ _vault.ansible_become_pass }}"
        cachable: yes
      no_log: yes

    - name: debug
      debug:
        msg: "{{ inventory_hostname }} {{ ansible_host }} {{ _internal_hosts[inventory_hostname].name }}"

    - name: Add nignx repo
      yum_repository:
        name: nginx
        description: Nginx repository
        # TODO: Parametrize os version
        baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
        enabled: no
        gpgcheck: no  # TODO: Fix?
      become: yes

    - name: Install nginx
      # Use yum module to use enablerepo feature
      yum:
        name: nginx
        enablerepo: nginx
      become: yes


    - name: Start nginx
      service:
        name: nginx
      become: yes

    - name: Stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      become: yes


  roles:
    - role: internal_network
      vars:
        internal_network: "{{ _internal_network }}"
        internal_network_ip4: "{{ _internal_hosts[inventory_hostname].ipv4 }}"

    - role: etc_hosts
      vars:
        etc_hosts_hosts: "{{ _internal_hosts }}"


- name: Cloudera Manager
  # Use name instead of "role", because there are very few hosts
  # and one host do many things
  hosts: fugen01
  # hosts: cm

  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

    - name: Set ansible_become_pass
      set_fact:
        ansible_become_pass: "{{ _vault.ansible_become_pass }}"
        cachable: yes
      no_log: yes

  roles:
    - role: cdh-mariadb
    - role: cloudera_manager
