---
- name: Setup fugen
  hosts: default
  vars:
    _hoe: fue
    internal_network:
      conn_name: eth1
      ifname: eth1
      gw4: 172.16.100.1
      ip_v4: 172.16.100.100
      subnetmask_prefix: 24

  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

    - name: Set ansible_become_pass
      set_fact:
        ansible_become_pass: "{{ _vault.ansible_become_pass }}"
        cachable: yes
      no_log: yes

    - name: debug
      debug:
        msg: "{{ _hoe }} {{ inventory_hostname }} {{ ansible_host }}"

    - name: Add nignx repo
      yum_repository:
        name: nginx
        description: Nginx repository
        # TODO: Parametrize os version
        baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
        enabled: no
        gpgcheck: no  # TODO: Fix?
      become: yes

    - name: Install nginx
      # Use yum module to use enablerepo feature
      yum:
        name: nginx
        enablerepo: nginx
      become: yes


    - name: Start nginx
      service:
        name: nginx
      become: yes

    - name: Stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      become: yes

    - name: Install packages for nmcli module
      package:
        name:
          - NetworkManager-glib
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
      become: yes

      # This modify network-script BOOTPROTO=static back to BOOTPROTO=dhcp?
      # TODO: This task always flag up changed?
    - name: Configure internal network
      nmcli:
        conn_name: "{{ internal_network.conn_name }}"
        ifname: "{{ internal_network.ifname }}"
        type: ethernet
        ip4: "{{ internal_network.ip_v4 }}/{{ internal_network.subnetmask_prefix }}"
        gw4: "{{ internal_network.gw4 }}"
        state: present
        autoconnect: yes
      become: yes

      # TODO: Restart network service
      # https://github.com/ansible/ansible/issues/36615#issuecomment-403239275
    - name: ansible bug fix for static ip
      replace:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ internal_network.ifname }}
        regexp: 'BOOTPROTO=dhcp'
        replace: 'BOOTPROTO=static'
        backup: yes
      become: yes
