---
ghost0:
  image: ghost:alpine
  container_name: ghost0
  ports:
    - "2368:2368"
  environment:
    NODE_ENV: production
  volumes:
    - "./config.js:/var/lib/ghost/config.js"
    - "/var/lib/data/docker/ghost0/data:/var/lib/ghost/content"
