---

- name: Install utilities for docker
  yum:
    name: "{{ item }}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: yes

- name: Add docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install docker
  yum:
    name: docker-ce
    update_cache: yes
  become: yes

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- include: user.yml

- include: pm2.yml

- name: Add docker_weekly_removal cron
  template:
    src: docker_weekly_removal.sh.j2
    dest: /etc/cron.weekly/docker-weekly-removal
    mode: "0755"
  become: yes
