---
  # TODO: Parametrize group and user name
- name: Create docker group
  group:
    name: docker
  become: yes

- name: Create docker user
  user:
    name: docker
    shell: /bin/bash
    groups: docker
    append: yes
  become: yes
