FROM debian

RUN apt-get update && apt-get install -y liquidsoap

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
RUN mkdir -p /var/run/liquidsoap
USER liquidsoap

CMD ["/entrypoint.sh"]
