---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources.yaml
# bases:
#   - base

namespace: exposed
commonLabels:
  kustomize: webtools
namePrefix: webtools-

configMapGenerator:
  - name: configmap-files
    files:
      - files/nginx_cmd.sh
      - files/nginx_index.html
      - files/settings.toml.envsubst
      # - files/webtools_command.sh
      - files/webtools_init.sh
  - name: configmap-for-env
    literals:
      - MINIO_ACCESS_KEY=17C2C6DB
      - WEBTOOLS_SETTINGS_TOML_ENVSUBST=/configmap_files/settings.toml.envsubst
      - WEBTOOLS_AWS_ACCESS_KEY_ID=17C2C6DB
      - WEBTOOLS_SQLITE3_PATH=/db.sqlite3
      - WEBTOOLS_ALLOWED_HOST=halt2.net
      - WEBTOOLS_AWS_S3_CUSTOM_DOMAIN_HOSTNAME=halt2.net

secretGenerator:
  - name: secret-files
    files:
      - secrets/minio_secret_key
      - secrets/webtools_secret_key

vars:
  - name: REDIS_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: redis-service
    fieldref:
      fieldpath: metadata.name
  - name: MINIO_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: minio-service
    fieldref:
      fieldpath: metadata.name


images:
  - name: webtools
    newName: quay.io/10sr/webtools
    newTag: v0.0.18
