---
version: '3'
services:
  app:
    image: cowrie/cowrie
    ports:
      - "22:2222"
    # volumes:
    #   - "./config.production.json:/var/lib/ghost/config.production.json:ro"
    #   - "/var/lib/data/docker/ghost0/data:/var/lib/ghost/content"
