version: '3'
services:
  zoo1:
    image: zookeeper:3.4
    container_name: zoo1
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - "/var/lib/data/docker/kafka/zoo1/data:/data"
      - "/var/lib/data/docker/kafka/zoo1/datalog:/datalog"

  zoo2:
    image: zookeeper:3.4
    container_name: zoo2
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - "/var/lib/data/docker/kafka/zoo2/data:/data"
      - "/var/lib/data/docker/kafka/zoo2/datalog:/datalog"

  zoo3:
    image: zookeeper:3.4
    container_name: zoo3
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - "/var/lib/data/docker/kafka/zoo3/data:/data"
      - "/var/lib/data/docker/kafka/zoo3/datalog:/datalog"
