---
#global: {}

# https://www.techscore.com/blog/2017/12/07/prometheus-monitoring-setting/
route:
  # receiver: ルート名の指定
  receiver: httppost
  # group_by: アラートを同じ種類とみなす条件
  # この場合、アラート名で判定されます
  group_by: [NodeInstanceDown]
  # group_wait: 同じ種類のアラートを1つのアラート群としてにまとめる時間
  group_wait:      10s
  # group_interval: 同じ種類のアラートが発生した時に次回通知するまでの時間
  group_interval:  5m
  # repeat_interval:正常に発砲されたアラートが再度通知されるまでの時間
  repeat_interval: 1h

receivers:
  - name: httppost
    webhook_configs:
      - url: 'http://3ends.info'
        send_resolved: true
