---
version: '3'
services:
  app:
    image: prom/prometheus:v2.8.0
    ports:
      - "127.0.0.1:9090:9090"
    environment: {}
    user: "1000"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh:ro"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/var/lib/data/docker/prometheus0/data:/prometheus:Z"
    # entrypoint: sh /entrypoint.sh
    # command:
    #   # Same as default
    #   - "-config.file=/etc/prometheus/prometheus.yml"
    #   - "-storage.local.path=/prometheus"
    #   - "-web.console.libraries=/etc/prometheus/console_libraries"
    #   - "-web.console.templates=/etc/prometheus/consoles"
