---
version: '3'
services:
  # TODO: Add nginx to proxy requests by path
  prom:
    image: prom/prometheus:v2.8.0
    ports:
      - "127.0.0.1:9090:9090"
    environment: {}
    user: "1000"
    volumes:
      # - "./entrypoint.sh:/entrypoint.sh:ro"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./rules.yml:/etc/prometheus/rules.yml:ro"
      # TODO: chown 1000 this directory
      - "/var/lib/data/docker/prometheus0/data:/prometheus"
    # entrypoint: sh /entrypoint.sh
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.external-url=https://pt.3ends.info/pt/
      - --web.route-prefix=/pt/

  am:
    image: prom/alertmanager:v0.16.2
    ports:
      - "127.0.0.1:9093:9093"
    user: "1000"
    volumes:
      - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro"
      # TODO: chown 1000 this directory
      - "/var/lib/data/docker/prometheus0/am:/alertmanager"
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=https://pt.3ends.info/am/
      - --web.route-prefix=/am/

  nginx:
    image: nginx
    ports:
      # - "127.0.0.1:"
      - "9089:9089"
    volumes:
      - ./nginx.conf.envsubst:/etc/nginx/nginx.conf.envsubst:ro
      - ./nginx_cmd.sh:/nginx_cmd.sh:ro
    command: sh /nginx_cmd.sh
    depends_on:
      - prom
      - am
