---
# https://kazuhira-r.hatenablog.com/entry/2019/02/11/205455
# https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
groups:
  - name: g1
    rules:
    - alert: NodeInstanceDown
      expr: up{job='node'} < 1
      for: 30s

    - alert: HighLA
      expr: node_load1{job='node'} > 50
      # for: 30s
