---
- name: Create unit file
  template:
    dest: /etc/systemd/system/{{ item.name }}.service
    src: unit.service.j2
  vars:
    unit: "{{ item.unitfile.unit }}"
    service: "{{ item.unitfile.service }}"
    install: "{{ item.unitfile.install }}"
  loop: "{{ systemd_service_services }}"
  become: yes
  register: _unit_file

- name: daemon-reload
  command: systemctl daemon-reload
  become: yes
  when: _unit_file is changed

# TODO: Restart when unit file updated

- name: Set states
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop: "{{ systemd_service_services }}"
  become: yes
