---
# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.5
      - test-3.6

_test-body: &test-body
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install dependent things
        command: make install
    - run:
        name: Run tests
        command: make check

jobs:
  test-2.7:
    <<: *test-body
    docker:
      - image: circleci/python:2.7
  test-3.5:
    <<: *test-body
    docker:
      - image: circleci/python:3.5
  test-3.6:
    <<: *test-body
    docker:
      - image: circleci/python:3.6
