---
- import_tasks: install.yaml
- import_tasks: default_root.yaml
# - import_tasks: basic_auth.yaml
- import_tasks: configs.yaml

- service:
    name: nginx
    enabled: yes
    state: started
  become: yes
