---
- name: Install mariadb
  yum:
    name: mariadb-server
  become: yes


  # TODO: Copy to /etc/my.cnf/d
# - name: Put mariadb confifg file
#   template:
#     src: my.cnf.j2
#     dest: /etc/my.cnf
#   become: yes
#   register: _my_cnf

# - name: Restart maridb
#   service:
#     name: mariadb
#     state: restarted
#   become: yes
#   when: _my_cnf.changed

- name: Start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes
