---
- name: Install required packages
  apt:
    name: "{{ item }}"
  become: yes
  with_items:
    - python-jenkins
    - python-lxml

- name: Generate kick-jenkins-jobs
  jenkins_job:
    config: "{{ lookup('template', 'templates/job.xml.j2') }}"
    name: "{{ kick_jenkins_jobs_name }}"
    user: "{{ kick_jenkins_jobs_web_username }}"
    password: "{{ kick_jenkins_jobs_web_password }}"
    url: http://localhost:8080
