---
- hosts: local
  vars:
    ansible_connection: local
  vars_files:
    - vars.yml
  tasks:
    - add_host:
        name: "{{ item.key }}"
        groups: lxc
      with_dict: "{{ containers }}"
      changed_when: no


- hosts: lxc
  vars:
    ansible_become_pass: "{{ lxc_become_pass }}"
    ansible_user: cdh
    ansible_connection: ssh
    ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/lxc"
  vars_files:
    - ./vault/lxc_become_pass.yml

  tasks:
    - debug:
        msg: hoe
      become: yes
