---
- hosts: local
  vars:
    ansible_connection: local
  vars_files:
    - vars.yml
    - ./vault/lxc_become_pass.yml
  tasks:
    - add_host:
        name: "{{ item.key }}"
        groups: lxc
        ansible_become_pass: "{{ lxc_become_pass }}"
        ansible_user: cdh
        ansible_connection: ssh
        ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/lxc"
        # http://qiita.com/taka379sy/items/331a294d67e02e18d68d
        ansible_ssh_extra_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      with_dict: "{{ containers }}"
      no_log: true
      changed_when: no


- hosts: lxc
  vars_files:
    - vars.yml
  tasks:
    - debug:
        msg: hoe
      become: yes

  roles:
    - role: hosts
      hosts_hosts: "{{ containers }}"

- hosts: cdh-db
  vars:
    cdh_mariadb_user_username: scm
    cdh_mariadb_cmf_dbname: scm
  vars_files:
    - ./vault/cdh_mariadb_root_password.yml
    - ./vault/cdh_mariadb_user_password.yml
  roles:
    - role: cdh-mariadb


- hosts: cm01
  vars:
    cdh_mariadb_user_username: scm
    cdh_mariadb_cmf_dbname: scm
  vars_files:
    - ./vault/cdh_mariadb_root_password.yml
    - ./vault/cdh_mariadb_user_password.yml
    - ./vault/lxc_become_pass.ypml

  roles:
    - role: cloudera_manager
      cdh_mariadb_db_host: cdh-db
