---
- hosts: opti
  vars:
    ansible_become_pass: "{{ opti_become_pass }}"
  vars_files:
    - ./vault/opti_become_pass.yml
    - ./vault/ddns_f5_si_password.yml
    - ./vault/lxc_ssh_secret_key.yml

  pre_tasks:
    # すべての role の前提として見込まれるもの
    - yum:
        name: "@Development Tools"
      become: yes
    - yum:
        name: python2-pip
      become: yes

  roles:
    - role: ddns_f5_si
      ddns_domain_name: 10sr.f5.si
      ddns_f5_si_name: 10sr
      ddns_f5_si_password_: "{{ ddns_f5_si_password }}"

    - role: mail

    - role: lxc
      lxc_containers:
        cm01:
          ip_address: 172.16.1.20
          configs:
            lxc.network.hwaddr: fe:db:c9:89:ff:e1
            lxc.network.ipv4: 172.16.1.20/24
        dn01:
          ip_address: 172.16.1.31
          configs:
            lxc.network.hwaddr: fe:61:bf:4d:3d:d7
            lxc.network.ipv4: 172.16.1.31/24
        dn02:
          ip_address: 172.16.1.32
          configs:
            lxc.network.hwaddr: fe:8f:14:73:35:e1
            lxc.network.ipv4: 172.16.1.32/24
        dn03:
          ip_address: 172.16.1.33
          configs:
            lxc.network.hwaddr: fe:e0:5e:81:04:d5
            lxc.network.ipv4: 172.16.1.33/24
        nn01:
          ip_address: 172.16.1.41
          configs:
            lxc.network.hwaddr: fe:bb:d2:70:f5:2f
            lxc.network.ipv4: 172.16.1.41/24
        nn02:
          ip_address: 172.16.1.42
          configs:
            lxc.network.hwaddr: fe:80:ac:ce:2d:9a
            lxc.network.ipv4: 172.16.1.42/24
        nn03:
          ip_address: 172.16.1.430
          configs:
            lxc.network.hwaddr: fe:b4:30:cd:75:98
            lxc.network.ipv4: 172.16.1.43/24

  tasks:
    - name: Install some utilities
      yum:
        name: "{{ item }}"
      with_items:
        - yum-utils
      become: yes

    - name: Install ansible
      pip:
        name: ansible
        executable: /usr/bin/pip2
      become: yes

    - name: Put ssh secret key
      copy:
        content: "{{ lxc_ssh_secret_key }}"
        dest: ./.ssh/lxc
        mode: "0600"
      no_log: yes
