---
- name: Add key for jenkins repository
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
  become: yes

- name: Add jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    update_cache: yes
  become: yes

- name: Install jenkins
  apt:
    name: jenkins
  become: yes

- name: Create custom init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes
  become: yes

- name: Add Jenkins init hook scripts
  template:
    src: "{{ item }}.groovy.j2"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item }}.groovy"
    owner: jenkins
    group: jenkins
  with_items:
    - basic-security
    - plugins
  become: yes
  no_log: yes
  notify: JENKINS_RESTART


- name: Start jenkins
  service:
    name: jenkins
  become: yes


  # TODO: Install plugins in init script
- name: Install jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
  with_items: "{{ jenkins_plugins }}"
  no_log: yes
  notify: JENKINS_RESTART
  ignore_errors: yes

# https://support.cloudbees.com/hc/en-us/articles/219257077-CSRF-Protection-Explained
# - name: Restart jenkins safely
#   uri:
#     url: http://localhost:8080/safeRestart
#     method: POST
#     force_basic_auth: yes
#     user: "{{ jenkins_admin_username }}"
#     password: "{{ jenkins_admin_password }}"
#   when: _jenkins_plugin is changed
