---
- name: Create directory for archive files
  file:
    # TODO: Parameterize
    path: /var/lib/machine-setups/roles/jenkins
    state: directory
  become: yes


- name: Fetch jenkins package
  get_url:
    # TODO: parameterize
    # TODO: Add checksum
    url: https://pkg.jenkins.io/debian/binary/jenkins_2.183_all.deb
    checksum: sha512:096a3ff69eb9fb7279eb3756ef54077f16fefd704c1e2f83518367d06f029a9356b3083ec0f35a7d036da0ef68a6e94d09bde66d54cb910bbaa72afdceff32ac
    dest: /var/lib/machine-setups/roles/jenkins
  register: _fetch_result
  become: yes

- name: Install jenkins
  apt:
    deb: "{{ _fetch_result.dest }}"
    # when: _fetch_result is changed
  become: yes

- name: Add JAVA_ARGS
  # https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties
  # Cannot use init groovy to set system properties
  # To get properties, jenkins.util.SystemProperties can be used
  # https://javadoc.jenkins.io/jenkins/util/SystemProperties.html
  blockinfile:
    path: /etc/default/jenkins
    marker: "# {mark} Managed by machine-setups/sakura"
    block: |
      JAVA_ARGS="$JAVA_ARGS {{ jenkins_java_args }}"
    insertafter: EOF
  become: yes

- name: Create custom init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes
  become: yes

- name: Add Jenkins init hook scripts
  template:
    src: "{{ item }}.groovy.j2"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item }}.groovy"
    owner: jenkins
    group: jenkins
  with_items:
    # TODO: Add basic configurations
    # TODO: Add num to order script
    - basic-security
    - plugins
    - theme
    - authorize-project
  become: yes
  no_log: yes
  notify: JENKINS_SAFERESTART


- name: Start jenkins
  service:
    name: jenkins
  become: yes
