---
- name: Add key for jenkins repository
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
  become: yes

- name: Add jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    update_cache: yes
  become: yes

- name: Install jenkins
  apt:
    name: jenkins
  become: yes

- name: Create custom init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: jenkins
    group: jenkins
    recurse: yes
  become: yes

- name: Add Jenkins init hook scripts
  template:
    src: "{{ item }}.groovy.j2"
    dest: "{{ jenkins_home }}/init.groovy.d/{{ item }}.groovy"
    owner: jenkins
    group: jenkins
  with_items:
    # TODO: Add basic configurations
    # TODO: Add num to order script
    - basic-security
    - plugins
    - theme
    - authorize-project
  become: yes
  no_log: yes
  notify: JENKINS_SAFERESTART


  # TODO: Temporarily disable Jenkins service
- name: Start jenkins
  service:
    name: jenkins
    state: stopped
    enabled: false
  become: yes
