---
- name: Setup jenkins user
  user:
    name: jenkins
    password: "{{ jenkins_user_password | password_hash('sha512', jenkins_user_password_salt) }}"
    groups: sudo
    append: yes
  become: yes
