---
- include: supervisor.yml

- hosts: all
  vars:
    saku_tarball: https://github.com/shingetsu/saku/archive/release-4.6.0.tar.gz
    home: "{{ansible_env.HOME}}"
    saku_tarball_path: "{{ansible_env.HOME}}/saku-4.6.0.tar.gz"
    saku_dest: "{{ansible_env.HOME}}/saku-4.6.0"
    saku_path: "{{saku_dest}}/saku-release-4.6.0"
    saku_port: 8000

  tasks:
    - name: Install python3
      apt: name=python3 state=present

    - name: Download saku tarball
      get_url: url={{saku_tarball}} dest={{saku_tarball_path}}

    - name: Make saku dir
      file: path={{saku_dest}} state=directory

    - name: Unpack saku tarball
      unarchive: copy=no src={{saku_tarball_path}} dest={{saku_dest}} creates={{saku_path}}/saku.py

    - name: Update saku config
      template: src=saku/saku.ini.j2 dest={{saku_path}}/file/saku.ini
      notify:
        - Restart saku

    - name: Add supervisor conf
      sudo: yes
      template: src=saku/supervisor.conf.j2 dest=/etc/supervisor/conf.d/saku.conf

    - name: Start saku with supervisor
      sudo: yes
      supervisorctl: name=saku state=present

    - name: Add nginx conf
      sudo: yes
      template: src=saku/nginx.conf.j2 dest=/etc/nginx/conf.d/saku.conf
      notify:
        - Restart nginx


  handlers:
    - name: Restart nginx
      sudo: yes
      service: name=nginx state=restarted

    - name: Restart saku
      sudo: yes
      supervisorctl: name=saku state=restarted
