# ---
# - name: Assert nginx installed
#   command: nginx -v
#   changed_when: false

# - name: Assert git installed
#   command: which git
#   changed_when: false

# - name: Create /opt directory
#   file:
#     dest: /opt
#     state: directory
#   become: yes

# - name: Clone certbot repository
#   git:
#     repo: https://github.com/certbot/certbot.git
#     dest: /opt/letsencrypt_certbot
#     force: yes
#     # Why no?
#     #update: no
#   diff: no
#   become: yes

- name: Install certbot
  package:
    name:
      - certbot
      - python3-certbot-dns-google
  become: yes

- name: Create certbot script
  template:
    src: _certbot-auto.sh.j2
    dest: /usr/local/bin/_certbot-auto.sh
  become: yes
  register: _certbot_auto_sh

- name: Create google dns sa cred file
  copy:
    dest: "{{ letsencrypt_google_dns_sa_cred_file }}"
    content: "{{ letsencrypt_google_dns_sa_cred_json }}"
    mode: "0600"
  become: yes

# - command: sh /usr/local/bin/_certbot-auto.sh
#   # args:
#   #   creates: "{{ letsencrypt_key_dir }}"
#   become: yes
#   when: _certbot_auto_sh is changed

# `sudo sh /usr/local/bin/_certbot-auto.sh` will create this directory
# Run this before proceeding
- name: Check key directory
  command: file {{ letsencrypt_key_dir }}
  changed_when: false

- name: Add cron schedule of certbot renew
  template:
    src: update_letsencrypt_cert.sh.j2
    dest: /etc/cron.weekly/update-letsencrypt-cert
    mode: "0755"
  become: yes

# http://qiita.com/ww24/items/9fa19594b4e3a8eb9b6f
- name: generate dhparam file
  command: openssl dhparam -out {{ letsencrypt_ssl_dhparam_path }} 2048
  args:
    creates: "{{ letsencrypt_ssl_dhparam_path }}"
  become: yes

- name: Remove ssl config in nginx.conf
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s*)(ssl_.*)$'
    replace: '\1# \2'
  become: yes

- name: Create nginx ssl config file
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  become: yes
  register: _ssl_conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
  when: _ssl_conf is changed
