---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/webtools.yaml
# bases:
#   - base

namespace: exposed
commonLabels:
  kustomize: exposed
nameSuffix: -exposed

configMapGenerator:
  - name: configmap-from-envfile
    env: configs.env
  - name: configmap-from-file-content
    files:
      - files/data.txt
      - files/nginx_cmd.sh
      - files/nginx_index.html
