---
version: '3'
services:
  app:
    image: gitbucket/gitbucket:4
    ports:
      - "0.0.0.0:29418:29418"
      - "127.0.0.1:9080:8080"
    environment: {}
    volumes:
      - "./start.sh:/start.sh:ro"
      - "/var/lib/data/docker/gitbucket0/:/gitbucket"
    # command: sh /start.sh
