FROM fluent/fluentd:latest

USER root

RUN apk add --update --virtual .build-deps build-base ruby-dev
RUN gem install ruby-kafka -v 0.3.16
RUN gem install zookeeper -v 1.4.11
RUN gem install fluent-plugin-kafka -v 0.5.3
RUN gem install fluent-plugin-retag
