---
version: "3"
services:
  fluentd0:
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./config:/fluentd/etc"
      - "/var/lib/data/docker/fluentd0/log:/fluentd/log"
      - "/var/lib/data/docker/fluentd0/pos_file:/fluentd/pos_file"
      - "/var/log:/rootfs/var_log:ro"
    environment:
      FLUENTD_CONF: fluentd.conf
    env_file:
      - ../fluentd.env
    extra_hosts:
      - "kafka0:192.168.101.100"
    networks:
      fluentd_net:
        ipv4_address: 192.168.102.100

networks:
  fluentd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.102.0/24
