---
version: "3"
services:
  fluentd0:
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    user: root
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./config:/fluentd/etc"
      - "/var/lib/data/docker/fluentd0/log:/fluentd/log"
      - "/var/lib/data/docker/fluentd0/pos_file:/fluentd/pos_file"
      - "/var/log:/rootfs/var_log:ro"
    environment:
      FLUENTD_CONF: fluentd.conf
