---
- include: install.yml

- apt:
    name: python3-pip
  become: yes

- pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  with_items:
    - docker
    - docker-compose
  become: yes

- file:
    dest: /root/docker-compose-test2/
    state: directory
  become: yes
  
- copy:
    dest: /root/docker-compose-test2/
    src: "{{ docker_compose_path }}/"
  become: yes

- template:
    dest: "/root/docker-compose-test2/{{ item.key }}.env"
    src: local.env.j2
  with_dict: "{{ docker_compose_env }}"
  become: yes
