---
- include: install.yml

- apt:
    name: python3-pip
  become: yes

- pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  with_items:
    - docker
    - docker-compose
  become: yes

  # TODO: Parametrize group and user name
- group:
    name: docker
  become: yes

- user:
    name: docker
    shell: /bin/bash
    groups: docker
    append: yes
  become: yes

- file:
    dest: /home/docker/docker-compose/
    state: directory
    owner: docker
  become: yes
  
- copy:
    dest: /home/docker/docker-compose/
    src: "{{ docker_compose_path }}/"
    owner: docker
  become: yes

- template:
    dest: "/home/docker/docker-compose/{{ item.key }}.env"
    src: local.env.j2
    owner: docker
  with_dict: "{{ docker_compose_env }}"
  become: yes

- template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/conf.d/{{ item.key }}.conf
  with_dict: "{{ docker_compose_supervisord }}"
  become: yes
  register: _docker_compose_supervisord

- command: supervisorctl update
  become: yes
  when: "{{ _docker_compose_supervisord.changed }}"

- supervisorctl:
    name: "docker_{{ item.key }}"
    state: present
  with_dict: "{{ docker_compose_supervisord }}"
  become: yes

# - supervisorctl:
#     name: "docker_{{ item.key }}"
#     state: started
#   with_dict: "{{ docker_compose_supervisord }}"
#   become: yes


- cron:
    name: Remove containers
    weekday: 6
    hour: 7
    minute: 20
    job: "docker ps -a --filter status=exited --quiet | xargs docker rm"
    user: root
  become: yes

- cron:
    name: Remove images
    weekday: 6
    hour: 7
    minute: 50
    job: "docker images --no-trunc=true --filter dangling=true --quiet | xargs docker rmi"
    user: root
  become: yes
