---
- include: install.yml

- apt:
    name: python3-pip
  become: yes

- pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  with_items:
    - docker
    - docker-compose
  become: yes

  # TODO: Parametrize group and user name
- group:
    name: docker
  become: yes

- user:
    name: docker
    shell: /bin/bash
    groups: docker
    append: yes
  become: yes

- file:
    dest: /home/docker/docker-compose/
    state: directory
    owner: docker
  become: yes
  
- copy:
    dest: /home/docker/docker-compose/
    src: "{{ docker_compose_path }}/"
    owner: docker
  become: yes

- template:
    dest: "/home/docker/docker-compose/{{ item.key }}.env"
    src: local.env.j2
    owner: docker
  with_dict: "{{ docker_compose_env }}"
  become: yes
