---
- include: install.yml

- apt:
    name: python3-pip
  become: yes

- pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  with_items:
    - docker
    - docker-compose
  become: yes

  # TODO: Parametrize group and user name
- group:
    name: docker
  become: yes

- user:
    name: docker
    shell: /bin/bash
    groups: docker
    append: yes
  become: yes

- file:
    dest: /home/docker/docker-compose/
    state: directory
    owner: docker
  become: yes
  
- copy:
    dest: /home/docker/docker-compose/
    src: "{{ docker_compose_path }}/"
    owner: docker
  become: yes

- template:
    dest: "/home/docker/docker-compose/{{ item.key }}.env"
    src: local.env.j2
    owner: docker
  vars:
    variables: "{{ item.value }}"
  with_dict: "{{ docker_compose_env }}"
  become: yes

- template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/conf.d/docker_programs.conf
  vars:
    programs: "{{ docker_compose_supervisord }}"
  become: yes
  register: _docker_compose_supervisord

- command: supervisorctl update
  become: yes
  when: "{{ _docker_compose_supervisord.changed }}"

- supervisorctl:
    name: "docker_{{ item.key }}"
    state: present
  with_dict: "{{ docker_compose_supervisord }}"
  become: yes

# - supervisorctl:
#     name: "docker_{{ item.key }}"
#     state: started
#   with_dict: "{{ docker_compose_supervisord }}"
#   become: yes

- apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes

- apt_repository:
    repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main' 
    update_cache: yes
  become: yes

- apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main' 
    update_cache: yes
  become: yes

- apt:
    name: nodejs
    state: latest
  become: yes

- npm:
    name: pm2
    path: /home/docker/_pm2
  become: yes
  become_user: docker

- template:
    src: docker_weekly_removal.sh.j2
    dest: /etc/cron.weekly/docker-weekly-removal
    mode: "0755"
  become: yes
