---
# TODO: Use safeRestart
- name: Restart jenkins
  service:
    name: jenkins
    state: restarted
  become: yes
  listen: JENKINS_RESTART

- name: Restart Jenkins Safely
  command: ssh {{ jenkins_webuser_username }}@localhost -p 2244 safe-restart
  beomce: no
  listen: JENKINS_SAFERESTART
