---
- name: Create directory
  file:
    # TODO: Parameterize
    path: /opt/prometheus_node_exporter
    state: directory
  become: yes

- name: Download tarball
  get_url:
    # TODO: Add checksum
    # TODO: parameterize
    url: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /opt/prometheus_node_exporter
  register: _fetch_result
  become: yes

- name: Unarchive tarall
  # TODO: How to know extracted file path?
  unarchive:
    src: "{{ _fetch_result.dest }}"
    dest: /opt/prometheus_node_exporter
    remote_src: yes
  become: yes
