version: '3'

services:
  db:
    image: mariadb:10
    command: ["--innodb-buffer-pool-size=128M", "--expire-logs-days=5"]
    volumes:
      - /var/lib/data/docker/nextcloud0/mariadb:/var/lib/mysql
    env_file:
      - ../nextcloud0.env

  redis:
    image: redis

  app:
    build:
      context: .
      dockerfile: Dockerfile.nextcloud
    volumes:
      - /var/lib/data/docker/nextcloud0/html:/var/www/html
      - ./local.config.php:/local.config.php:ro
      - ./redis.config.php:/redis.config.php:ro
    environment:
      - MYSQL_HOST=db
    env_file:
      - ../nextcloud0.env
    depends_on:
      - db
      - redis

  web:
    image: nginx
    ports:
      - 8888:8888
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/data/docker/nextcloud0/html:/var/www/html:ro
    depends_on:
      - app

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    user: www-data
    env_file:
      - ../nextcloud0.env
    volumes:
      - /var/lib/data/docker/nextcloud0/html:/var/www/html
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
