---
- name: Create directory for config files
  file:
    path: /etc/traefik
    state: directory
  become: yes

- name: Create directory for data files
  file:
    path: /var/lib/traefik
    state: directory
  become: yes


- name: Create dynamic provider file
  template:
    src: providers.toml.j2
    dest: /etc/traefik/providers.toml
  become: yes

- name: Create static config file
  template:
    src: traefik.toml.j2
    dest: /etc/traefik/traefik.toml
  become: yes

- name: Create service account file for gcloud DNS
  copy:
    content: "{{ traefik_gcloud_sa_content }}"
    dest: /etc/traefik/sa.json
  become: yes

- name: Start traefik service
  service:
    name: traefik
    enabled: true
  become: yes
