---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          command: [ "sh", "/configmap_volume/nginx_cmd.sh" ]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: configmap-from-file-content-volume
              mountPath: /configmap_volume
      volumes:
        - name: configmap-from-file-content-volume
          configMap:
            name: configmap-from-file-content
