---
- hosts: default
  vars:
    # Do not use these variables directly in roles!
    ubuntu_codename: xenial
    # domain_name: 3ends.info
    domain_name: "tk2-407-44672.vs.sakura.ne.jp"
  vars_files:
    - ./vault/ansible_become_pass.yml

  pre_tasks:
    - name: Check codename
      assert:
        that:
          - ubuntu_codename == ansible_lsb.codename
          - ubuntu_codename == ansible_distribution_release

  roles:
    # - role: hostname
    #   hostname: "{{ domain_name }}"

    - role: letsencrypt
      letsencrypt_register_email: 8.slashes@gmail.com
      letsencrypt_domain_names:
        - "{{ domain_name }}"
      letsencrypt_webroot: /var/nginx/main
      letsencrypt_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_dhparam_path: /etc/ssl/private/dhparam.pem

    - role: nginx
      nginx_main_server_names:
        - "{{ domain_name }}"
      nginx_main_root: /var/nginx/main
      nginx_ssl_main_root: /var/nginx/main
      nginx_letsencrypt_access_dir: /.well-known/acme-challenge
      nginx_letsencrypt_webroot: /var/nginx/main
      nginx_ssl_main_server_name: "{{ domain_name }}"

    - role: docker
      docker_ubuntu_codename: "{{ ubuntu_codename }}"
      docker_compose_path: ./docker-compose
      docker_compose_env: {}
      docker_pm2: {}
