---
- hosts: default
  vars:
    # Do not use these variables directly in roles!
    ubuntu_codename: xenial
    # domain_name: 3ends.info
    domain_name: "tk2-407-44672.vs.sakura.ne.jp"
  vars_files:
    - ./vault/ansible_become_pass.yml
    - ./vault/bot_post_bearer_token.yml
    - ./vault/bot_twitter_secret.yml
    - ./vault/bot_twitter_token_secret.yml

  pre_tasks:
    - name: Check codename
      assert:
        that:
          - ubuntu_codename == ansible_lsb.codename
          - ubuntu_codename == ansible_distribution_release

    - name: Install some prerequisite packages
      apt:
        name: "{{ item }}"
      with_items:
        - git
        - nginx
      become: yes

  roles:
    # - role: hostname
    #   hostname: "{{ domain_name }}"

    - role: letsencrypt
      letsencrypt_register_email: 8.slashes@gmail.com
      letsencrypt_domain_names:
        - "{{ domain_name }}"
      letsencrypt_webroot: /var/nginx/main
      letsencrypt_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_dhparam_path: /etc/ssl/private/dhparam.pem

    - role: nginx
      nginx_main_server_names:
        - "{{ domain_name }}"
      nginx_main_root: /var/nginx/main
      nginx_ssl_main_root: /var/nginx/main
      nginx_letsencrypt_access_dir: /.well-known/acme-challenge
      nginx_letsencrypt_webroot: /var/nginx/main
      nginx_ssl_main_server_name: "{{ domain_name }}"

    - role: docker
      docker_ubuntu_codename: "{{ ubuntu_codename }}"
      docker_compose_path: ./docker-compose
      docker_compose_env:
        10sr_bot0:
          TWITTER_KEY: VmHRoeyCxmGisuGPCBADVfo6v
          TWITTER_SECRET: "{{ bot_twitter_secret }}"
          TWITTER_TOKEN: 2578716006-LhQWcRQyG5r0uC92yLwy1LYhNIPGMVXAy4CWOpt
          TWITTER_TOKEN_SECRET: "{{ bot_twitter_token_secret }}"
          POST_BEARER_TOKEN: "{{ bot_post_bearer_token }}"
      docker_pm2:
        10sr_bot0:
          json: 10sr_bot0/pm2.json
          state: started
          command: docker-compose up --build
        ghost0:
          json: ghost0/pm2.json
          state: started
          command: docker-compose up --force-recreate

    - role: postfix
      postfix_root_alias: 8.slashes@gmail.com
