---
apiVersion: v1
kind: Service
metadata:
  name: webtools-redis-service
spec:
  type: ClusterIP
  selector:
    app: webtools
    service: redis
  ports:
    - port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-redis-deployment
  labels:
    app: webtools
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtools
      service: redis
  template:
    metadata:
      labels:
        app: webtools
        service: redis
    spec:
      containers:
        - name: webtools-redis
          image: redis
