---
- file:
    dest: "{{ nginx_ssl_main_root }}"
    state: directory
    recurse: yes
  become: yes

- copy:
    src: index.html
    dest: "{{ nginx_ssl_main_root }}/index_ssl.html"
  become: yes

- template:
    src: main_ssl.conf.j2
    dest: /etc/nginx/conf.d/main_ssl.conf
  become: yes
  register: _nginx_ssl_conf

- service:
    name: nginx
    state: restarted
  become: yes
  when: "{{ _nginx_ssl_conf.changed }}"
