---
- apt:
    name: icecast2
  become: yes

# TODO: Setup password

- lineinfile:
    dest: /etc/icecast2/icecast.xml
    regexp: "<source-password>.*</source-password>"
    line: "        <source-password>{{ secret.icecast2_source_password }}</source-password>"
  become: yes
  when: secret.icecast2_source_password != ""
  notify: Restart icecast2

- lineinfile:
    dest: /etc/icecast2/icecast.xml
    regexp: "<relay-password>.*</relay-password>"
    line: "        <relay-password>{{ secret.icecast2_relay_password }}</relay-password>"
  become: yes
  when: secret.icecast2_relay_password != ""
  notify: Restart icecast2

- lineinfile:
    dest: /etc/icecast2/icecast.xml
    regexp: "<admin-password>.*</admin-password>"
    line: "        <admin-password>{{ secret.icecast2_admin_password }}</admin-password>"
  become: yes
  when: secret.icecast2_admin_password != ""
  notify: Restart icecast2

- lineinfile:
    dest: /etc/icecast2/icecast.xml
    regexp: "<hostname>.*</hostname>"
    line: "    <hostname>{{ icecast2_server_name }}</hostname>"
  become: yes
  notify: Restart icecast2

- lineinfile:
    dest: /etc/icecast2/icecast.xml
    regexp: "<port>.*</port>"
    line: "        <port>{{ icecast2_server_port }}</port>"
  become: yes
  notify: Restart icecast2

- service:
    name: icecast2
    enabled: yes
    state: started
  become: yes
  # service icecast2 start return 1 when icecast2 has been already started
  # so ignore the exit status. Fearful.
  failed_when: false

- template:
    src: icecast2.conf.j2
    dest: /etc/nginx/conf.d/icecast2.conf
  become: yes
  notify: Restart nginx
