---
- apt:
    name: icecast2
  become: yes

# TODO: Setup password

- template:
    src: icecast.xml.j2
    dest: /etc/icecast2/icecast.xml
  become: yes
  when:
    secret.icecast2_source_password != "" and
    secret.icecast2_relay_password != "" and
    secret.icecast2_admin_password != ""
  register: icecast2_update_config
  notify: Restart icecast2

- lineinfile:
    dest: /etc/default/icecast2
    regexp: "^ENABLE="
    line: "ENABLE=true"
  become: yes
  when: icecast2_update_config.skipped is not defined

- service:
    name: icecast2
    enabled: yes
    state: started
  become: yes
  # service icecast2 start return 1 when icecast2 has been already started
  # so ignore the exit status. Fearful.
  failed_when: false

- template:
    src: icecast2.conf.j2
    dest: /etc/nginx/conf.d/icecast2.conf
  become: yes
  notify: Restart nginx
