FROM nextcloud:11-fpm

# Requred for https source
RUN apt-get update && apt-get install -y apt-transport-https

RUN curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
RUN echo "deb https://deb.nodesource.com/node_6.x jessie main" >>/etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install -y nodejs
RUN npm install -g cron-cli
