---
- template: src=regtomydns.sh.j2 mode=0755 dest={{mydns_regtomydns_path}}
  when: mydns_password != ""
  become: yes
- name: Check if regtomydns works
  command: "{{mydns_regtomydns_path}}"
  changed_when: False
