---
- file:
    dest: /opt
    state: directory
  become: yes

- git:
    repo: https://github.com/certbot/certbot.git
    version: v0.8.0
    dest: /opt/letsencrypt_certbot
    force: yes
  become: yes

- template:
    src: _certbot-auto.sh.j2
    dest: /usr/local/bin/_certbot-auto.sh
  become: yes

- service:
    name: nginx
    state: started
  become: yes

- command: sh /usr/local/bin/_certbot-auto.sh
  args:
    creates: "{{ letsencrypt_key_dir }}"
  become: yes

# It fails. Why?????????????????
# Adding like this with sudo crontab -e works anyway.
# #Ansible: Update letsencrypt cert
# 10 4 15 * * /opt/letsencrypt_certbot/certbot-auto renew && service nginx restart
# - cron:
#     name: Update letsencrypt cert
#     day: 15
#     hour: 4
#     minute: 10
#     job: /opt/letsencrypt_certbot/certbot-auto renew && service nginx restart
#     user: root
#   become: yes

# http://qiita.com/ww24/items/9fa19594b4e3a8eb9b6f
- command: openssl dhparam -out {{ letsencrypt_ssl_dhparam_path }} 2048
  args:
    creates: "{{ letsencrypt_ssl_dhparam_path }}"
  become: yes

- template:
    src: ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  become: yes
  notify: Restart nginx
