---
- file:
    dest: /opt
    state: directory
  become: yes

- git:
    repo: https://github.com/certbot/certbot.git
    version: v0.8.0
    dest: /opt/letsencrypt_certbot
    force: yes
  become: yes

# - template:
#     src: letsencrypt.conf.j2
#     dest: /etc/nginx/conf.d/letsencrypt.conf
#   become: yes
#   notify: Restart nginx

# http://qiita.com/ww24/items/9fa19594b4e3a8eb9b6f
- command: openssl dhparam -out /etc/ssl/private/dhparam.pem 2048
  args:
    creates: /etc/ssl/private/dhparam.pem
  become: yes

- service:
    name: nginx
    state: started
  become: yes
