---
- name: gcp debug
  hosts: all
  tasks:
    - debug:
        msg: "Hostname: {{ ansible_nodename }}"

- name: Setup front host
  hosts: label_role_front
  vars:
    _domain_name: halt2.net
  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

    # - name: Install packages
    #   apt:
    #     name: git
    #   become: yes

  roles:
    - name: k3s
      vars: {}

    # - name: nginx
    #   vars:
    #     nginx_basic_auth_htpasswd: []

    #     # non ssl
    #     nginx_default_root: /var/nginx/main
    #     nginx_name_ssl_only:
    #       - "jk.{{ _domain_name }}"

    #     nginx_host_proxies:
    #       - name: k8s-nginx.{{ _domain_name }}
    #         port: 30080
    #     nginx_proxy_upstreams: []

    #     # ssl
    #     nginx_ssl_default_root: /var/nginx/main
    #     nginx_ssl_proxy_upstreams: []
    #     nginx_ssl_host_proxies:
    #       - name: k8s-nginx.{{ _domain_name }}
    #         port: 30080

    - role: letsencrypt
      # need this?
      letsencrypt_webroot: /var/nginx/main
      letsencrypt_register_email: 8.slashes@gmail.com
      letsencrypt_domain_names:
        - "{{ _domain_name }}"
        - "*.{{ _domain_name }}"
      letsencrypt_certname: "{{ _domain_name }}"
      letsencrypt_key_dir: /etc/letsencrypt/live/{{ _domain_name }}
      letsencrypt_ssl_key_dir: /etc/letsencrypt/live/{{ _domain_name }}
      letsencrypt_ssl_dhparam_path: /etc/ssl/private/dhparam.pem

- name: Setup jenkins host
  hosts: label_jenkins_on
  pre_tasks:
    - debug:
        msg: "Hostname: {{ ansible_nodename }}"
  roles:
    - name: java_jre

    - name: jenkins
      vars:
        jenkins_deb:
          url: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.204.1_all.deb
          sha512: 76caa3218b72a8eea8dd98352ab862a935d832cc7d563a2db3da39ceaab4f0c3c47b6a036d7630a7a89da8af83c15bf647085138f7632fdceeccab5924cca466
