---
- name: Configure all hosts
  hosts: all
  tasks:
    - debug:
        msg: |
          Hostname: {{ ansible_nodename }}
          Name: {{ hostvars[inventory_hostname]["name"] }}

    - name: Uninstall nano
      package:
        name: nano
        state: absent
      become: yes

    - name: Install utils
      package:
        name:
          # dig
          - dnsutils
          - netcat
      become: yes

- name: Setup front host
  hosts: label_role_front
  vars:
    _domain_name: halt2.net

  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

    # - name: Install packages
    #   apt:
    #     name: git
    #   become: yes

  roles:
    - name: k3s
      vars: {}

    - name: nginx
      vars:
        # nginx_basic_auth_htpasswd: []

        # non ssl
        nginx_default_root: /var/nginx/main
        nginx_name_ssl_only:
          - "jk.{{ _domain_name }}"
        nginx_proxy_path_proxies: []
        nginx_host_proxies:
          - name: k8s-nginx.{{ _domain_name }}
            pass: "127.0.0.1:30080"

        # ssl
        nginx_ssl_default_root: /var/nginx/main
        nginx_ssl_path_proxies: []
        nginx_ssl_host_proxies:
          - name: k8s-nginx.{{ _domain_name }}
            pass: "127.0.0.1:30080"
          - name: jk.{{ _domain_name }}
            pass: "jenkins01:8080"
            additional_directives:
              - "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for"
              - "proxy_set_header X-Forwarded-Host $host"
              - "proxy_set_header X-Forwarded-Server $host"
              - "proxy_set_header X-Forwarded-Proto $scheme"
              - "proxy_set_header X-Real-IP $remote_addr"

    - role: letsencrypt
      # need this?
      letsencrypt_webroot: /var/nginx/main
      letsencrypt_register_email: 8.slashes@gmail.com
      letsencrypt_domain_names:
        - "{{ _domain_name }}"
        - "*.{{ _domain_name }}"
      letsencrypt_certname: "{{ _domain_name }}"
      letsencrypt_key_dir: /etc/letsencrypt/live/{{ _domain_name }}
      letsencrypt_ssl_key_dir: /etc/letsencrypt/live/{{ _domain_name }}
      letsencrypt_ssl_dhparam_path: /etc/ssl/private/dhparam.pem

- name: Setup jenkins
  hosts: label_jenkins_on
  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

  roles:
    - name: java_jre
      vars: {}

    - name: jenkins
      vars:
        jenkins_deb:
          url: https://pkg.jenkins.io/debian-stable/binary/jenkins_2.249.1_all.deb
          sha512: 3fa05ff20b46493aac8ebe67f96938e2c88833945dbefa8f89499bc484542d352dfbe5cbd56cc1f910ad238fd589bb14aa8f1b90d024bf264f7b83cf8152eac0

        jenkins_webuser_username: admin
        jenkins_webuser_password: "{{ _vault.jenkins_webuser_password }}"
        # TODO: This value is too big so separete into file
        jenkins_webuser_ssh_publickey:
          # Key of remote ansible normal user
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtbZCbsB2JSHD8DSShyZOC0SMIx3aDMO30IxGsyGTc+B42QmSoSuD3k1MU1edQ0JRoxpSPCHQrd+Sn+sgPiDzagK9jHsrzwr4nvqVNZ3XOXEjFe9Alf3qkIAbGEHk63HzuA/g3CsXfhPpUPWdG3CnbiddDLfkWCdcI5eTH7tdewuwKF+yh9VbDl9ZPV7P5EInAvQDtxhJnRjOYJ5b3TIYGNeGeo5mFUncKUO3nhi1EWiOquJAo0X2a8ieDEBL5RIqzT/AgKZ+qW2Xh1OvF9v7RpGGPcLHaT50gwieFsaRzJuShMCvaO+XmL4DTg7J7d4o/GfzervDHuzH8cF1AQLV7 admin@jenkins01

        # jenkins_serveruser_password: "{{ _vault.jenkins_serveruser_password }}"
        # jenkins_serveruser_password_salt: "{{ ansible_mounts.0.uuid.replace('-', '')[:16] }}"

        jenkins_plugins:
          - ansicolor
          # - job-dsl
          # - authorize-project
          - simple-theme-plugin
          - slack
          - prometheus

        # https://github.com/afonsof/jenkins-material-theme/
        jenkins_theme_css_url: https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-cyan.css

        # https://issues.jenkins-ci.org/browse/JENKINS-10160
        # https://stackoverflow.com/questions/31740373/how-can-i-prevent-that-the-jenkins-log-gets-spammed-with-strange-messages
        # https://www.ionutgavrilut.com/2018/jenkins-floods-with-DNS-errors/
        jenkins_java_args: >-
          -Dhudson.DNSMultiCast.disabled=true
          -Dhudson.udp=-1

- name: Setup postfix
  hosts: label_postfix_on
  pre_tasks:
    - name: Include all vault variables
      include_vars:
        dir: ./vault/
        name: _vault
      no_log: yes

  roles:
    - name: postfix
      vars:
        # Allow relay from asia-northeast01 VPC
        postfix_mynetwork: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.146.0.0/20"
        postfix_smtp_hostname: smtp.mailgun.org
        postfix_smtp_port: 587
        postfix_smtp_login: postmaster@m.halt2.net
        postfix_smtp_password: "{{ _vault.mailgun_smtp_password }}"
        postfix_root_alias: 8.slashes@gmail.com
