---
- hosts: default
  vars:
    ubuntu_codename: trusty
    domain_name: 10sr.f5.si
    secret:
      # Overwritten by secret.yml
      ddns_mydns_password: ""
      ddns_f5_si_password: ""
      icecast2_source_password: ""
      icecast2_relay_password: ""
      icecast2_admin_password: ""
  roles:
    #- apt-upgrade
    - ddns

    - role: nginx
      nginx_main_server_names:
        - "{{ domain_name }}"
        - 10sr.mydns.jp
      nginx_main_root: /var/nginx/main

    - role: icecast2
      icecast2_server_name: ic.{{ domain_name }}
      icecast2_letsencrypt_access_dir: /.well-known/acme-challenge
      icecast2_letsencrypt_webroot: /var/nginx/main

    - role: letsencrypt
      letsencrypt_domain_names:
        - "{{ domain_name }}"
        - ic.{{ domain_name }}
        #- d.{{ domain_name }}
      letsencrypt_webroot: /var/nginx/main
      letsencrypt_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_dhparam_path: /etc/ssl/private/dhparam.pem

    - role: nginx_ssl
      nginx_ssl_main_server_name: "{{ domain_name }}"
      nginx_ssl_main_root: /var/nginx/main

    - role: icecast2_ssl
      icecast2_ssl_server_name: ic."{{ domain_name }}"
      icecast2_ssl_upstream_name: icecast2

    - supervisord

    - role: dokku
      dokku_domain_name: d.{{ domain_name }}

    - role: lxc
      lxc_user: "{{ ansible_user_id }}"
      lxc_user_dir: "{{ ansible_user_dir }}"
      lxc_virbr_name: lxcbr0
      lxc_nic_num: 10
      lxc_subuid_start: 100000
      lxc_subuid_range: 65536
      lxc_subgid_start: 100000
      lxc_subgid_range: 65536
