---
- hosts: default
  vars:
    ubuntu_codename: trusty
    dokku_domain_name: d.10sr.f5.si
  roles:
    #- apt-upgrade
    - role: nginx
      nginx_main_server_names:
        - 10sr.f5.si
        - 10sr.mydns.jp
      nginx_main_root: /var/nginx/main
    - role: letsencrypt
      letsencrypt_domain_names:
        - 10sr.f5.si
        - d.10sr.f5.si
        - ic.10sr.f5.si
      letsencrypt_webroot: /var/nginx/main
    - mydns
    - supervisord
    - role: icecast
      icecast2_server_name: ic.10sr.f5.si
      icecast2_letsencrypt_access_dir: /.well-known/acme-challenge
      icecast2_letsencrypt_webroot: /var/nginx/main
    - dokku
    - role: lxc
      lxc_user: "{{ ansible_user_id }}"
      lxc_user_dir: "{{ ansible_user_dir }}"
      lxc_virbr_name: lxcbr0
      lxc_nic_num: 10
      lxc_subuid_start: 100000
      lxc_subuid_range: 65536
      lxc_subgid_start: 100000
      lxc_subgid_range: 65536
