---
- hosts: default
  vars:
    ubuntu_codename: trusty
    dokku_domain_name: d.10sr.mydns.jp
  roles:
    - apt-upgrade
    - role: nginx
      nginx_main_server_name: 10sr.mydns.jp
    - letsencrypt
    - mydns
    - supervisord
    - icecast
    - dokku
    - role: lxc
      lxc_user: "{{ ansible_user_id }}"
      lxc_user_dir: "{{ ansible_user_dir }}"
      lxc_virbr_name: lxcbr0
      lxc_nic_num: 10
      lxc_subuid_start: 100000
      lxc_subuid_range: 65536
      lxc_subgid_start: 100000
      lxc_subgid_range: 65536
