#!/usr/bin/env ansible-playbook --ask-become-pass
---
- hosts: default
  vars:
    # Do not use these variables directly in roles!
    ubuntu_codename: trusty
    domain_name: 3ends.info
    secret:
      # Overwritten by secret.yml
      ddns_mydns_password: ""
      ddns_f5_si_password: ""
      icecast2_source_password: ""
      icecast2_relay_password: ""
      icecast2_admin_password: ""
  roles:
    - role: hostname
      hostname: "{{ domain_name }}"

    - role: data_dir
      data_dir_dirs:
        - mountpoint: /data
          filepath: /data.fs
          size_mb: 15000
      

    #- apt-upgrade
    - role: ddns
      ddns_domain_name: 10sr.f5.si
      ddns_name: 10sr

    - role: nginx
      nginx_main_server_names:
        - "{{ domain_name }}"
        - 10sr.f5.si
        - 10sr.mydns.jp
      nginx_main_root: /var/nginx/main
      # not used yet
      nginx_proxy_upstreams: []

    - role: icecast2
      icecast2_server_name: ic.{{ domain_name }}
      icecast2_server_port: 3389
      icecast2_letsencrypt_access_dir: /.well-known/acme-challenge
      icecast2_letsencrypt_webroot: /var/nginx/main
      icecast2_liquidsoap_sources:
        - name: the_back_horn
          playlist: "/var/icecast2/THE BACK HORN/all.m3u"
        - name: ring_all
          playlist: /var/icecast2/ring/all.m3u
        - name: lovelive_all
          playlist: /var/icecast2/lovelive/all.m3u
        - name: lovelive_best1
          playlist: /var/icecast2/lovelive/lovelive_best1/all.m3u
        - name: lovelive_best2
          playlist: /var/icecast2/lovelive/lovelive_best2/all.m3u

    - role: letsencrypt
      letsencrypt_domain_names:
        - "{{ domain_name }}"
        - ic.{{ domain_name }}
        #- d.{{ domain_name }}
      letsencrypt_webroot: /var/nginx/main
      letsencrypt_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_key_dir: /etc/letsencrypt/live/{{ domain_name }}
      letsencrypt_ssl_dhparam_path: /etc/ssl/private/dhparam.pem

    - role: nginx_ssl
      nginx_ssl_main_server_name: "{{ domain_name }}"
      nginx_ssl_main_root: /var/nginx/main
      nginx_ssl_proxy_upstreams:
        - path: /wiki
          port: 4567
        - path: /minio
          port: 9000

    - role: icecast2_ssl
      icecast2_ssl_server_name: ic."{{ domain_name }}"
      icecast2_ssl_upstream_name: icecast2

    - role: supervisord

    - role: wiki
      wiki_user: wiki
      wiki_path: /wiki
      wiki_port: 4567

    # disable dokku for now: dokku should be updated!
    # - role: dokku
    #   dokku_domain_name: d.{{ domain_name }}

    - role: lxc
      lxc_user: "{{ ansible_user_id }}"
      lxc_user_dir: "{{ ansible_user_dir }}"
      lxc_virbr_name: lxcbr0
      lxc_nic_num: 10
      lxc_subuid_start: 100000
      lxc_subuid_range: 65536
      lxc_subgid_start: 100000
      lxc_subgid_range: 65536

    - role: docker
      compose_templates:
        - name: minio
          src: ./docker-compose/minio.yml.j2
      minio_access_key: key
      minio_secret_key: secret
      minio_port: 9000

    - role: postfix
