---
- template:
    src: mastodon_proxy.conf.j2
    dest: /etc/nginx/conf.d/mastodon_proxy.conf
  become: yes
  register: _mastodon_proxy

- service:
    name: nginx
    state: restarted
  when: _mastodon_proxy.changed
  become: yes
